swagger: '2.0'
info:
  version: '1.0.0'
  title: Test Run System
schemes: [http]
consumes: [application/json, multipart/form-data]
produces: [application/json]
securityDefinitions:
  authorization:
    type: apiKey
    in: header
    name: Authorization

paths:
  # health
  /health:
    $ref: ./path/v1/health/health.yml

  # authentication
  /v1/register:
    $ref: ./path/v1/auth/register.yml

  /v1/login:
    $ref: ./path/v1/auth/login.yml

  # product
  /v1/product:
    $ref: ./path/v1/product/product.yml
  
  /v1/product/{product_id}:
    $ref: ./path/v1/product/product_id.yml
  
  /v1/product/{product_id}/stock:
    $ref: ./path/v1/product/product_id.stock.yml

definitions:
  principal:
    type: object
    properties:
      username:
        type: string
      user_id:
        type: number
        format: uint64
      expired_at:
        type: string
        format: date-time

  product:
    allOf:
      - $ref: "./definitions/common.yml#/definitions/ModelIdentifier"
      - $ref: "./definitions/common.yml#/definitions/ModelTrackTime"
      - $ref: "./definitions/common.yml#/definitions/ModelTrackBy"
      - $ref: "./definitions/product.yml#/definitions/productData"

  productActivityHistory:
    allOf:
      - $ref: "./definitions/common.yml#/definitions/ModelIdentifier"
      - $ref: "./definitions/product_activity_history.yml#/definitions/productActivityHistoryData"

  user:
    allOf:
      - $ref: "./definitions/common.yml#/definitions/ModelIdentifier"
      - $ref: "./definitions/common.yml#/definitions/ModelTrackTime"
      - $ref: "./definitions/user.yml#/definitions/userData"
