consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    version: 1.0.0
    title: Test Run System
paths:
    /health:
        get:
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                "200":
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                    description: Health Check
                default:
                    description: Server Error
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
    /v1/product:
        post:
            description: Create new product
            tags:
                - product
            summary: Create New
            operationId: createProduct
            parameters:
                - name: data
                  in: body
                  schema:
                    type: object
                    required:
                        - name
                        - stock
                    properties:
                        expiry_date:
                            type: string
                            pattern: ^(0[1-9]|[12][0-9]|3[01])[- -.](0[1-9]|1[012])[- /.](19|20)\d\d$
                            description: format date DD-MM-YYYY
                        name:
                            type: string
                        stock:
                            type: number
                            format: uint64
                            minimum: !!float 1
            responses:
                "201":
                    description: Success create
                    schema:
                        allOf:
                            - type: object
                              properties:
                                message:
                                    type: string
                            - type: object
                              properties:
                                product_id:
                                    type: number
                                    format: uint64
                default:
                    description: Server Error
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
            security: []
    /v1/product/{product_id}:
        put:
            operationId: updateProduct
            parameters:
                - description: product_id
                  name: product_id
                  in: path
                  required: true
                  type: integer
                  format: uint64
                  default: !!float 1
                - in: body
                  schema:
                    type: object
                    required:
                        - name
                    properties:
                        name:
                            type: string
                        expiry_date:
                            description: format date DD-MM-YYYY
                            type: string
                            pattern: ^(0[1-9]|[12][0-9]|3[01])[- -.](0[1-9]|1[012])[- /.](19|20)\d\d$
                  name: data
            responses:
                "201":
                    description: Success update
                    schema:
                        allOf:
                            - type: object
                              properties:
                                message:
                                    type: string
                default:
                    description: Server Error
                    schema:
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
                        type: object
            security: []
            description: Update existing product
            tags:
                - product
            summary: Update
        delete:
            summary: Delete
            operationId: deleteProduct
            parameters:
                - required: true
                  type: integer
                  format: uint64
                  default: !!float 1
                  description: product_id
                  name: product_id
                  in: path
            responses:
                "201":
                    description: Success update
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                default:
                    description: Server Error
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
            security: []
            description: Delete product
            tags:
                - product
definitions:
    principal:
        type: object
        properties:
            user_id:
                type: number
                format: uint64
            email:
                type: string
            expired_at:
                type: string
    product:
        allOf:
            - type: object
              required:
                - id
              properties:
                id:
                    format: uint64
                    type: integer
            - type: object
              properties:
                created_at:
                    x-go-custom-tag: gorm:"column:created_at"
                    x-nullable: true
                    x-omitempty: false
                    type: string
                    format: date-time
                deleted_at:
                    x-omitempty: false
                    type: string
                    format: date-time
                    x-go-custom-tag: gorm:"column:deleted_at"
                    x-nullable: true
                updated_at:
                    type: string
                    format: date-time
                    x-go-custom-tag: gorm:"column:updated_at"
                    x-nullable: true
                    x-omitempty: false
            - type: object
              properties:
                created_by:
                    type: string
                    x-omitempty: false
                deleted_by:
                    type: string
                    x-omitempty: false
                updated_by:
                    type: string
                    x-omitempty: false
            - type: object
              properties:
                expiry_date:
                    type: string
                    format: date-time
                name:
                    x-omitempty: false
                    type: string
                stock:
                    type: number
                    format: uint64
                version:
                    format: uint64
                    type: number
    productActivityHistory:
        allOf:
            - required:
                - id
              properties:
                id:
                    format: uint64
                    type: integer
              type: object
            - type: object
              properties:
                type:
                    type: string
                created_at:
                    type: string
                    format: date-time
                    x-omitempty: false
                created_by:
                    type: string
                    x-omitempty: false
                note:
                    type: string
                product:
                    allOf:
                        - required:
                            - id
                          properties:
                            id:
                                type: integer
                                format: uint64
                          type: object
                        - type: object
                          properties:
                            created_at:
                                format: date-time
                                x-go-custom-tag: gorm:"column:created_at"
                                x-nullable: true
                                x-omitempty: false
                                type: string
                            deleted_at:
                                type: string
                                format: date-time
                                x-go-custom-tag: gorm:"column:deleted_at"
                                x-nullable: true
                                x-omitempty: false
                            updated_at:
                                type: string
                                format: date-time
                                x-go-custom-tag: gorm:"column:updated_at"
                                x-nullable: true
                                x-omitempty: false
                        - type: object
                          properties:
                            created_by:
                                type: string
                                x-omitempty: false
                            deleted_by:
                                type: string
                                x-omitempty: false
                            updated_by:
                                type: string
                                x-omitempty: false
                        - type: object
                          properties:
                            expiry_date:
                                type: string
                                format: date-time
                            name:
                                type: string
                                x-omitempty: false
                            stock:
                                format: uint64
                                type: number
                            version:
                                type: number
                                format: uint64
                product_id:
                    type: number
                    format: uint64
    productActivityHistoryData:
        type: object
        properties:
            created_at:
                type: string
                format: date-time
                x-omitempty: false
            created_by:
                type: string
                x-omitempty: false
            note:
                type: string
            product:
                allOf:
                    - type: object
                      required:
                        - id
                      properties:
                        id:
                            type: integer
                            format: uint64
                    - type: object
                      properties:
                        created_at:
                            type: string
                            format: date-time
                            x-go-custom-tag: gorm:"column:created_at"
                            x-nullable: true
                            x-omitempty: false
                        deleted_at:
                            x-omitempty: false
                            type: string
                            format: date-time
                            x-go-custom-tag: gorm:"column:deleted_at"
                            x-nullable: true
                        updated_at:
                            format: date-time
                            x-go-custom-tag: gorm:"column:updated_at"
                            x-nullable: true
                            x-omitempty: false
                            type: string
                    - type: object
                      properties:
                        created_by:
                            x-omitempty: false
                            type: string
                        deleted_by:
                            x-omitempty: false
                            type: string
                        updated_by:
                            type: string
                            x-omitempty: false
                    - type: object
                      properties:
                        expiry_date:
                            type: string
                            format: date-time
                        name:
                            type: string
                            x-omitempty: false
                        stock:
                            type: number
                            format: uint64
                        version:
                            type: number
                            format: uint64
            product_id:
                type: number
                format: uint64
            type:
                type: string
    productData:
        type: object
        properties:
            expiry_date:
                type: string
                format: date-time
            name:
                type: string
                x-omitempty: false
            stock:
                format: uint64
                type: number
            version:
                type: number
                format: uint64
securityDefinitions:
    key:
        type: apiKey
        name: Authorization
        in: header
