consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: Test Run System
    version: 1.0.0
paths:
    /health:
        get:
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                default:
                    description: Server Error
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
    /v1/product:
        post:
            security: []
            description: Create new product
            tags:
                - product
            summary: Create New
            operationId: createProduct
            parameters:
                - schema:
                    type: object
                    required:
                        - name
                        - stock
                    properties:
                        expiry_date:
                            description: format date DD-MM-YYYY
                            type: string
                            pattern: ^(0[1-9]|[12][0-9]|3[01])[- -.](0[1-9]|1[012])[- /.](19|20)\d\d$
                        name:
                            type: string
                        stock:
                            type: number
                            format: uint64
                            minimum: !!float 1
                  name: data
                  in: body
            responses:
                "201":
                    description: Success create
                    schema:
                        allOf:
                            - type: object
                              properties:
                                message:
                                    type: string
                            - type: object
                              properties:
                                product_id:
                                    type: number
                                    format: uint64
                default:
                    description: Server Error
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
    /v1/product/{product_id}:
        put:
            tags:
                - product
            summary: Update
            operationId: updateProduct
            parameters:
                - description: product_id
                  name: product_id
                  in: path
                  required: true
                  type: integer
                  format: uint64
                  default: !!float 1
                - name: data
                  in: body
                  schema:
                    required:
                        - name
                    properties:
                        expiry_date:
                            type: string
                            pattern: ^(0[1-9]|[12][0-9]|3[01])[- -.](0[1-9]|1[012])[- /.](19|20)\d\d$
                            description: format date DD-MM-YYYY
                        name:
                            type: string
                    type: object
            responses:
                "201":
                    description: Success update
                    schema:
                        allOf:
                            - type: object
                              properties:
                                message:
                                    type: string
                default:
                    description: Server Error
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
            security: []
            description: Update existing product
definitions:
    principal:
        type: object
        properties:
            email:
                type: string
            expired_at:
                type: string
            user_id:
                type: number
                format: uint64
    product:
        allOf:
            - required:
                - id
              properties:
                id:
                    type: integer
                    format: uint64
              type: object
            - type: object
              properties:
                deleted_at:
                    type: string
                    format: date-time
                    x-omitempty: false
                updated_at:
                    type: string
                    format: date-time
                    x-omitempty: false
                created_at:
                    x-omitempty: false
                    type: string
                    format: date-time
            - type: object
              properties:
                created_by:
                    type: string
                    x-omitempty: false
                deleted_by:
                    type: string
                    x-omitempty: false
                updated_by:
                    type: string
                    x-omitempty: false
            - type: object
              properties:
                stock:
                    format: uint64
                    type: number
                version:
                    type: number
                    format: uint64
                expiry_date:
                    format: date-time
                    type: string
                name:
                    type: string
                    x-omitempty: false
    productActivityHistory:
        allOf:
            - type: object
              required:
                - id
              properties:
                id:
                    type: integer
                    format: uint64
            - type: object
              properties:
                created_at:
                    type: string
                    format: date-time
                    x-omitempty: false
                created_by:
                    x-omitempty: false
                    type: string
                note:
                    type: string
                product:
                    allOf:
                        - type: object
                          required:
                            - id
                          properties:
                            id:
                                type: integer
                                format: uint64
                        - type: object
                          properties:
                            created_at:
                                type: string
                                format: date-time
                                x-omitempty: false
                            deleted_at:
                                type: string
                                format: date-time
                                x-omitempty: false
                            updated_at:
                                type: string
                                format: date-time
                                x-omitempty: false
                        - type: object
                          properties:
                            created_by:
                                type: string
                                x-omitempty: false
                            deleted_by:
                                type: string
                                x-omitempty: false
                            updated_by:
                                type: string
                                x-omitempty: false
                        - properties:
                            expiry_date:
                                type: string
                                format: date-time
                            name:
                                type: string
                                x-omitempty: false
                            stock:
                                type: number
                                format: uint64
                            version:
                                type: number
                                format: uint64
                          type: object
                product_id:
                    type: number
                    format: uint64
                type:
                    type: string
    productActivityHistoryData:
        type: object
        properties:
            product:
                allOf:
                    - properties:
                        id:
                            type: integer
                            format: uint64
                      type: object
                      required:
                        - id
                    - type: object
                      properties:
                        created_at:
                            format: date-time
                            x-omitempty: false
                            type: string
                        deleted_at:
                            type: string
                            format: date-time
                            x-omitempty: false
                        updated_at:
                            type: string
                            format: date-time
                            x-omitempty: false
                    - type: object
                      properties:
                        created_by:
                            type: string
                            x-omitempty: false
                        deleted_by:
                            type: string
                            x-omitempty: false
                        updated_by:
                            type: string
                            x-omitempty: false
                    - type: object
                      properties:
                        expiry_date:
                            type: string
                            format: date-time
                        name:
                            type: string
                            x-omitempty: false
                        stock:
                            type: number
                            format: uint64
                        version:
                            type: number
                            format: uint64
            product_id:
                type: number
                format: uint64
            type:
                type: string
            created_at:
                type: string
                format: date-time
                x-omitempty: false
            created_by:
                type: string
                x-omitempty: false
            note:
                type: string
    productData:
        type: object
        properties:
            expiry_date:
                format: date-time
                type: string
            name:
                type: string
                x-omitempty: false
            stock:
                format: uint64
                type: number
            version:
                format: uint64
                type: number
securityDefinitions:
    key:
        type: apiKey
        name: Authorization
        in: header
