consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    version: 1.0.0
    title: Test Run System
paths:
    /health:
        get:
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                default:
                    description: Server Error
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
                "200":
                    description: Health Check
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
            security: []
            description: Check if the App is Running
definitions:
    principal:
        type: object
        properties:
            user_id:
                type: number
                format: uint64
            email:
                type: string
            expired_at:
                type: string
securityDefinitions:
    key:
        name: Authorization
        in: header
        type: apiKey
