definitions:
  productData:
    type: object
    properties: 
      name:
        type: string
        x-omitempty: false
      stock:
        type: number
        format: uint64
      version:
        type: number
        format: uint64
      expiry_date:
        type: string
        format: date-time
        x-omitempty: false
        x-nullable: true